### ISSUE TITLE
IP saved in wrong format

### ISSUE THREAD

**Issue by g4m3r0** [open-classifieds/open-eshop#405]
IP Address is saved as integer inside the DB.

Is this a error or a kind of privacy protection?
Because a IP like "-1133354013" is unusable.

**Comment by neo22s** [comment]
Please review the guidelines for contributing to this repository.
https://github.com/open-classifieds/open-eshop/blob/master/CONTRIBUTING.md#reporting-issues

We store them in LONG since its the best way to store an IP ADDRESS rather than VARCHAR or CHAR.

You can retrieve from PHP using the long2ip or in MySQL  INET_NTOA.

read more at http://bafford.com/2009/03/09/mysql-performance-benefits-of-storing-integer-ip-addresses/
